//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ccMVCTesting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> ParentCategoryID { get; set; }
        public int CategoryColor { get; set; }
        public int UserID { get; set; }
        public string ParentCategoryName { get; set; }
    
        public virtual User User { get; set; }
    }
}
