//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ccMVCTesting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Categories = new HashSet<Category>();
        }
    
        public int UserID { get; set; }
        public string OriginalEMail { get; set; }
        public string CurrentEMail { get; set; }
        public System.DateTimeOffset Created { get; set; }
        public Nullable<System.DateTimeOffset> Confirmed { get; set; }
        public System.DateTimeOffset LastUpdated { get; set; }
        public Nullable<System.DateTimeOffset> LastLogin { get; set; }
        public bool Active { get; set; }
        public string OriginalPwd { get; set; }
        public string CurrentPwd { get; set; }
        public int FailedAttempts { get; set; }
        public Nullable<int> DefaultCurrencyID { get; set; }
        public Nullable<int> OriginalCountryID { get; set; }
        public Nullable<int> LastLoginCountryID { get; set; }
        public Nullable<int> LastFailedCountryID { get; set; }
        public string AuthUserID { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
    }
}
